### Configuration File for CIBR-FLARE Project
## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private:
    user-name:
    user-email:
## Container Settings
container:
  name: flare-process-noaa
  version: 21.01.4
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory:
## Container Paths
flare_path: /home/user/flare
flare_shared_path: /home/user/flare/shared
read_from_path: /home/user/flare/shared/flare-download-noaa # Path to the downloaded NOAA files. To directly download from NOMADS server, leave the path blank.
noaa_model: NOAAGEFS_6hr

## Parameters
downscale: TRUE
run_parallel: TRUE
overwrite: FALSE
num_cores: 8
forecast_date: .na
forecast_time: .na
lake_name_code: fcre
lake_name: Falling Creek Reservoir
lake_latitude: 37.307 # Degrees North
lake_longitude: 79.837 # Degrees West
## Openwhisk Settings
openwhisk:
  days-look-back: 1
  container-dependencies: "flare-download-noaa flare-process-noaa"
  next-trigger:
    name: flare-noaa-ready-fcre
    container_name: compound-trigger
    type: noaa
