## General Settings
git:
  remote:
    server: github.com
    branch: master
    ssh-key-private:
    user-name: 
    user-email: 
## Container Settings
container:
  name: send-email
  version: latest
  working-directory:
    pre-run-pull: FALSE
    post-run-push: FALSE
    git:
      remote:
        server: 192.168.20.20
        port:
        repository: FLARE-forecast/test-data
        branch: master
        directory:
gmail:
    username: "SENDER_EMAIL_ACCOUNT"
    password-hash: "SENDER_EMAIL_PASSWORD"
    from: "SENDER_NAME"
email:
    subject: "XXXX"
    body: "XXXX"
    attachments_github:
      - https://github.com/FLARE-forecast/SUNP-data/raw/sunp-graphs/sunpMetDataFigures_
      - https://github.com/FLARE-forecast/SUNP-data/raw/sunp-graphs/sunpWaterQualityDataFigures_
    attachments_local:
      - /home/ubuntu/test/local.txt
    recepients:
      - XXXX@gmail.com
      - XXXX@ufl.edu
