name: sunp-generate-graphs

# Controls when the action will run.
on:
  push:
    branches: [ master ]
  schedule:
    - cron:  '0 */7 * * *'


jobs: 
  generate-graphs:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Load repo and install R
    steps:
      - name: Checkout with sunp-generate-graphs branch
        uses: actions/checkout@v2
        with:
          repository: FLARE-forecast/SUNP-data
          ref: sunp-generate-graphs
          fetch-depth: 1

      - name: Set Up R
        uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: |
          R -e 'install.packages("lubridate")'
      - name: Run R Script
        run: Rscript sunp-generate-graphs.R
        
      # Commit files ,and push
      - name: Commit files
        run: |
          git config --local user.email "rebecca86420@gmail.com"
          git config --local user.name "Yun-Jung"
          git add sunpMetDataFigures_$(date '+%Y-%m-%d').pdf sunpWaterQualityDataFigures_$(date '+%Y-%m-%d').pdf
          git commit -m "sunp-generate-graphs-$(date '+%Y-%m-%d')" -a
      
      - name: Checkout with sunp-graphs branch
        uses: actions/checkout@v2
        with:
          repository: FLARE-forecast/SUNP-data
          ref: sunp-graphs
          fetch-depth: 1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: FLARE-forecast/SUNP-data
          branch: sunp-graphs
